var annotated_dup =
[
    [ "uhd", "namespaceuhd.html", [
      [ "convert", "namespaceuhd_1_1convert.html", [
        [ "converter", "classuhd_1_1convert_1_1converter.html", "classuhd_1_1convert_1_1converter" ],
        [ "id_type", "structuhd_1_1convert_1_1id__type.html", "structuhd_1_1convert_1_1id__type" ]
      ] ],
      [ "log", "namespaceuhd_1_1log.html", [
        [ "logging_info", "structuhd_1_1log_1_1logging__info.html", "structuhd_1_1log_1_1logging__info" ]
      ] ],
      [ "math", "namespaceuhd_1_1math.html", [
        [ "fp_compare", "namespaceuhd_1_1math_1_1fp__compare.html", [
          [ "fp_compare_delta", "classuhd_1_1math_1_1fp__compare_1_1fp__compare__delta.html", "classuhd_1_1math_1_1fp__compare_1_1fp__compare__delta" ],
          [ "fp_compare_epsilon", "classuhd_1_1math_1_1fp__compare_1_1fp__compare__epsilon.html", "classuhd_1_1math_1_1fp__compare_1_1fp__compare__epsilon" ]
        ] ]
      ] ],
      [ "rfnoc", "namespaceuhd_1_1rfnoc.html", [
        [ "block_ctrl", "classuhd_1_1rfnoc_1_1block__ctrl.html", null ],
        [ "block_ctrl_base", "classuhd_1_1rfnoc_1_1block__ctrl__base.html", "classuhd_1_1rfnoc_1_1block__ctrl__base" ],
        [ "block_id_t", "classuhd_1_1rfnoc_1_1block__id__t.html", "classuhd_1_1rfnoc_1_1block__id__t" ],
        [ "blockdef", "classuhd_1_1rfnoc_1_1blockdef.html", "classuhd_1_1rfnoc_1_1blockdef" ],
        [ "ddc_block_ctrl", "classuhd_1_1rfnoc_1_1ddc__block__ctrl.html", null ],
        [ "dma_fifo_block_ctrl", "classuhd_1_1rfnoc_1_1dma__fifo__block__ctrl.html", "classuhd_1_1rfnoc_1_1dma__fifo__block__ctrl" ],
        [ "duc_block_ctrl", "classuhd_1_1rfnoc_1_1duc__block__ctrl.html", null ],
        [ "fir_block_ctrl", "classuhd_1_1rfnoc_1_1fir__block__ctrl.html", "classuhd_1_1rfnoc_1_1fir__block__ctrl" ],
        [ "graph", "classuhd_1_1rfnoc_1_1graph.html", "classuhd_1_1rfnoc_1_1graph" ],
        [ "make_args_t", "structuhd_1_1rfnoc_1_1make__args__t.html", "structuhd_1_1rfnoc_1_1make__args__t" ],
        [ "node_ctrl_base", "classuhd_1_1rfnoc_1_1node__ctrl__base.html", "classuhd_1_1rfnoc_1_1node__ctrl__base" ],
        [ "null_block_ctrl", "classuhd_1_1rfnoc_1_1null__block__ctrl.html", "classuhd_1_1rfnoc_1_1null__block__ctrl" ],
        [ "radio_ctrl", "classuhd_1_1rfnoc_1_1radio__ctrl.html", "classuhd_1_1rfnoc_1_1radio__ctrl" ],
        [ "rate_node_ctrl", "classuhd_1_1rfnoc_1_1rate__node__ctrl.html", "classuhd_1_1rfnoc_1_1rate__node__ctrl" ],
        [ "replay_block_ctrl", "classuhd_1_1rfnoc_1_1replay__block__ctrl.html", "classuhd_1_1rfnoc_1_1replay__block__ctrl" ],
        [ "scalar_node_ctrl", "classuhd_1_1rfnoc_1_1scalar__node__ctrl.html", "classuhd_1_1rfnoc_1_1scalar__node__ctrl" ],
        [ "siggen_block_ctrl", "classuhd_1_1rfnoc_1_1siggen__block__ctrl.html", null ],
        [ "sink_block_ctrl_base", "classuhd_1_1rfnoc_1_1sink__block__ctrl__base.html", "classuhd_1_1rfnoc_1_1sink__block__ctrl__base" ],
        [ "sink_node_ctrl", "classuhd_1_1rfnoc_1_1sink__node__ctrl.html", "classuhd_1_1rfnoc_1_1sink__node__ctrl" ],
        [ "source_block_ctrl_base", "classuhd_1_1rfnoc_1_1source__block__ctrl__base.html", "classuhd_1_1rfnoc_1_1source__block__ctrl__base" ],
        [ "source_node_ctrl", "classuhd_1_1rfnoc_1_1source__node__ctrl.html", "classuhd_1_1rfnoc_1_1source__node__ctrl" ],
        [ "stream_sig_t", "classuhd_1_1rfnoc_1_1stream__sig__t.html", "classuhd_1_1rfnoc_1_1stream__sig__t" ],
        [ "terminator_node_ctrl", "classuhd_1_1rfnoc_1_1terminator__node__ctrl.html", "classuhd_1_1rfnoc_1_1terminator__node__ctrl" ],
        [ "tick_node_ctrl", "classuhd_1_1rfnoc_1_1tick__node__ctrl.html", "classuhd_1_1rfnoc_1_1tick__node__ctrl" ],
        [ "traffic_counter", "classuhd_1_1rfnoc_1_1traffic__counter.html", "classuhd_1_1rfnoc_1_1traffic__counter" ],
        [ "window_block_ctrl", "classuhd_1_1rfnoc_1_1window__block__ctrl.html", "classuhd_1_1rfnoc_1_1window__block__ctrl" ]
      ] ],
      [ "transport", "namespaceuhd_1_1transport.html", [
        [ "vrt", "namespaceuhd_1_1transport_1_1vrt.html", [
          [ "if_packet_info_t", "structuhd_1_1transport_1_1vrt_1_1if__packet__info__t.html", "structuhd_1_1transport_1_1vrt_1_1if__packet__info__t" ]
        ] ],
        [ "bounded_buffer", "classuhd_1_1transport_1_1bounded__buffer.html", "classuhd_1_1transport_1_1bounded__buffer" ],
        [ "bounded_buffer_detail", "classuhd_1_1transport_1_1bounded__buffer__detail.html", "classuhd_1_1transport_1_1bounded__buffer__detail" ],
        [ "buffer_pool", "classuhd_1_1transport_1_1buffer__pool.html", "classuhd_1_1transport_1_1buffer__pool" ],
        [ "if_addrs_t", "structuhd_1_1transport_1_1if__addrs__t.html", "structuhd_1_1transport_1_1if__addrs__t" ],
        [ "managed_buffer", "classuhd_1_1transport_1_1managed__buffer.html", "classuhd_1_1transport_1_1managed__buffer" ],
        [ "managed_recv_buffer", "classuhd_1_1transport_1_1managed__recv__buffer.html", "classuhd_1_1transport_1_1managed__recv__buffer" ],
        [ "managed_send_buffer", "classuhd_1_1transport_1_1managed__send__buffer.html", "classuhd_1_1transport_1_1managed__send__buffer" ],
        [ "muxed_zero_copy_if", "classuhd_1_1transport_1_1muxed__zero__copy__if.html", "classuhd_1_1transport_1_1muxed__zero__copy__if" ],
        [ "tcp_zero_copy", "structuhd_1_1transport_1_1tcp__zero__copy.html", "structuhd_1_1transport_1_1tcp__zero__copy" ],
        [ "udp_simple", "classuhd_1_1transport_1_1udp__simple.html", "classuhd_1_1transport_1_1udp__simple" ],
        [ "udp_zero_copy", "classuhd_1_1transport_1_1udp__zero__copy.html", "classuhd_1_1transport_1_1udp__zero__copy" ],
        [ "usb_control", "classuhd_1_1transport_1_1usb__control.html", "classuhd_1_1transport_1_1usb__control" ],
        [ "usb_device_handle", "classuhd_1_1transport_1_1usb__device__handle.html", "classuhd_1_1transport_1_1usb__device__handle" ],
        [ "usb_zero_copy", "classuhd_1_1transport_1_1usb__zero__copy.html", "classuhd_1_1transport_1_1usb__zero__copy" ],
        [ "zero_copy_flow_ctrl", "classuhd_1_1transport_1_1zero__copy__flow__ctrl.html", "classuhd_1_1transport_1_1zero__copy__flow__ctrl" ],
        [ "zero_copy_if", "classuhd_1_1transport_1_1zero__copy__if.html", "classuhd_1_1transport_1_1zero__copy__if" ],
        [ "zero_copy_recv_offload", "classuhd_1_1transport_1_1zero__copy__recv__offload.html", "classuhd_1_1transport_1_1zero__copy__recv__offload" ],
        [ "zero_copy_xport_params", "structuhd_1_1transport_1_1zero__copy__xport__params.html", "structuhd_1_1transport_1_1zero__copy__xport__params" ]
      ] ],
      [ "usrp", "namespaceuhd_1_1usrp.html", [
        [ "component_file_t", "structuhd_1_1usrp_1_1component__file__t.html", "structuhd_1_1usrp_1_1component__file__t" ],
        [ "dboard_base", "classuhd_1_1usrp_1_1dboard__base.html", "classuhd_1_1usrp_1_1dboard__base" ],
        [ "dboard_eeprom_t", "structuhd_1_1usrp_1_1dboard__eeprom__t.html", "structuhd_1_1usrp_1_1dboard__eeprom__t" ],
        [ "dboard_id_t", "classuhd_1_1usrp_1_1dboard__id__t.html", "classuhd_1_1usrp_1_1dboard__id__t" ],
        [ "dboard_iface", "classuhd_1_1usrp_1_1dboard__iface.html", "classuhd_1_1usrp_1_1dboard__iface" ],
        [ "dboard_iface_special_props_t", "structuhd_1_1usrp_1_1dboard__iface__special__props__t.html", "structuhd_1_1usrp_1_1dboard__iface__special__props__t" ],
        [ "dboard_manager", "classuhd_1_1usrp_1_1dboard__manager.html", "classuhd_1_1usrp_1_1dboard__manager" ],
        [ "fe_connection_t", "classuhd_1_1usrp_1_1fe__connection__t.html", "classuhd_1_1usrp_1_1fe__connection__t" ],
        [ "multi_usrp", "classuhd_1_1usrp_1_1multi__usrp.html", "classuhd_1_1usrp_1_1multi__usrp" ],
        [ "rx_dboard_base", "classuhd_1_1usrp_1_1rx__dboard__base.html", "classuhd_1_1usrp_1_1rx__dboard__base" ],
        [ "subdev_spec_pair_t", "structuhd_1_1usrp_1_1subdev__spec__pair__t.html", "structuhd_1_1usrp_1_1subdev__spec__pair__t" ],
        [ "subdev_spec_t", "classuhd_1_1usrp_1_1subdev__spec__t.html", "classuhd_1_1usrp_1_1subdev__spec__t" ],
        [ "tx_dboard_base", "classuhd_1_1usrp_1_1tx__dboard__base.html", "classuhd_1_1usrp_1_1tx__dboard__base" ],
        [ "xcvr_dboard_base", "classuhd_1_1usrp_1_1xcvr__dboard__base.html", "classuhd_1_1usrp_1_1xcvr__dboard__base" ]
      ] ],
      [ "usrp_clock", "namespaceuhd_1_1usrp__clock.html", [
        [ "multi_usrp_clock", "classuhd_1_1usrp__clock_1_1multi__usrp__clock.html", "classuhd_1_1usrp__clock_1_1multi__usrp__clock" ],
        [ "octoclock_eeprom_t", "classuhd_1_1usrp__clock_1_1octoclock__eeprom__t.html", "classuhd_1_1usrp__clock_1_1octoclock__eeprom__t" ]
      ] ],
      [ "utils", "namespaceuhd_1_1utils.html", [
        [ "scope_exit", "classuhd_1_1utils_1_1scope__exit.html", "classuhd_1_1utils_1_1scope__exit" ]
      ] ],
      [ "analog_filter_base", "classuhd_1_1analog__filter__base.html", "classuhd_1_1analog__filter__base" ],
      [ "analog_filter_lp", "classuhd_1_1analog__filter__lp.html", "classuhd_1_1analog__filter__lp" ],
      [ "assertion_error", "structuhd_1_1assertion__error.html", "structuhd_1_1assertion__error" ],
      [ "async_metadata_t", "structuhd_1_1async__metadata__t.html", "structuhd_1_1async__metadata__t" ],
      [ "clock_config_t", "structuhd_1_1clock__config__t.html", "structuhd_1_1clock__config__t" ],
      [ "device", "classuhd_1_1device.html", "classuhd_1_1device" ],
      [ "device3", "classuhd_1_1device3.html", "classuhd_1_1device3" ],
      [ "device_addr_t", "classuhd_1_1device__addr__t.html", "classuhd_1_1device__addr__t" ],
      [ "dict", "classuhd_1_1dict.html", "classuhd_1_1dict" ],
      [ "digital_filter_base", "classuhd_1_1digital__filter__base.html", "classuhd_1_1digital__filter__base" ],
      [ "digital_filter_fir", "classuhd_1_1digital__filter__fir.html", "classuhd_1_1digital__filter__fir" ],
      [ "dirty_tracked", "classuhd_1_1dirty__tracked.html", "classuhd_1_1dirty__tracked" ],
      [ "environment_error", "structuhd_1_1environment__error.html", "structuhd_1_1environment__error" ],
      [ "exception", "structuhd_1_1exception.html", "structuhd_1_1exception" ],
      [ "filter_info_base", "classuhd_1_1filter__info__base.html", "classuhd_1_1filter__info__base" ],
      [ "fs_path", "structuhd_1_1fs__path.html", "structuhd_1_1fs__path" ],
      [ "gain_fcns_t", "structuhd_1_1gain__fcns__t.html", "structuhd_1_1gain__fcns__t" ],
      [ "gain_group", "classuhd_1_1gain__group.html", "classuhd_1_1gain__group" ],
      [ "gps_ctrl", "classuhd_1_1gps__ctrl.html", "classuhd_1_1gps__ctrl" ],
      [ "i2c_iface", "classuhd_1_1i2c__iface.html", "classuhd_1_1i2c__iface" ],
      [ "image_loader", "classuhd_1_1image__loader.html", "classuhd_1_1image__loader" ],
      [ "index_error", "structuhd_1_1index__error.html", "structuhd_1_1index__error" ],
      [ "io_error", "structuhd_1_1io__error.html", "structuhd_1_1io__error" ],
      [ "io_type_t", "classuhd_1_1io__type__t.html", "classuhd_1_1io__type__t" ],
      [ "key_error", "structuhd_1_1key__error.html", "structuhd_1_1key__error" ],
      [ "lookup_error", "structuhd_1_1lookup__error.html", "structuhd_1_1lookup__error" ],
      [ "mac_addr_t", "classuhd_1_1mac__addr__t.html", "classuhd_1_1mac__addr__t" ],
      [ "meta_range_t", "structuhd_1_1meta__range__t.html", "structuhd_1_1meta__range__t" ],
      [ "msg_task", "classuhd_1_1msg__task.html", "classuhd_1_1msg__task" ],
      [ "narrowing_error", "structuhd_1_1narrowing__error.html", "structuhd_1_1narrowing__error" ],
      [ "not_implemented_error", "structuhd_1_1not__implemented__error.html", "structuhd_1_1not__implemented__error" ],
      [ "os_error", "structuhd_1_1os__error.html", "structuhd_1_1os__error" ],
      [ "otw_type_t", "structuhd_1_1otw__type__t.html", "structuhd_1_1otw__type__t" ],
      [ "property", "classuhd_1_1property.html", "classuhd_1_1property" ],
      [ "property_tree", "classuhd_1_1property__tree.html", "classuhd_1_1property__tree" ],
      [ "range_t", "classuhd_1_1range__t.html", "classuhd_1_1range__t" ],
      [ "ref_vector", "classuhd_1_1ref__vector.html", "classuhd_1_1ref__vector" ],
      [ "runtime_error", "structuhd_1_1runtime__error.html", "structuhd_1_1runtime__error" ],
      [ "rx_metadata_t", "structuhd_1_1rx__metadata__t.html", "structuhd_1_1rx__metadata__t" ],
      [ "rx_streamer", "classuhd_1_1rx__streamer.html", "classuhd_1_1rx__streamer" ],
      [ "sensor_value_t", "structuhd_1_1sensor__value__t.html", "structuhd_1_1sensor__value__t" ],
      [ "sid_t", "classuhd_1_1sid__t.html", "classuhd_1_1sid__t" ],
      [ "soft_register_base", "classuhd_1_1soft__register__base.html", "classuhd_1_1soft__register__base" ],
      [ "soft_register_sync_t", "classuhd_1_1soft__register__sync__t.html", "classuhd_1_1soft__register__sync__t" ],
      [ "soft_register_t", "classuhd_1_1soft__register__t.html", "classuhd_1_1soft__register__t" ],
      [ "soft_regmap_accessor_t", "classuhd_1_1soft__regmap__accessor__t.html", "classuhd_1_1soft__regmap__accessor__t" ],
      [ "soft_regmap_db_t", "classuhd_1_1soft__regmap__db__t.html", "classuhd_1_1soft__regmap__db__t" ],
      [ "soft_regmap_t", "classuhd_1_1soft__regmap__t.html", "classuhd_1_1soft__regmap__t" ],
      [ "spi_config_t", "structuhd_1_1spi__config__t.html", "structuhd_1_1spi__config__t" ],
      [ "spi_iface", "classuhd_1_1spi__iface.html", "classuhd_1_1spi__iface" ],
      [ "stream_args_t", "structuhd_1_1stream__args__t.html", "structuhd_1_1stream__args__t" ],
      [ "stream_cmd_t", "structuhd_1_1stream__cmd__t.html", "structuhd_1_1stream__cmd__t" ],
      [ "syntax_error", "structuhd_1_1syntax__error.html", "structuhd_1_1syntax__error" ],
      [ "system_error", "structuhd_1_1system__error.html", "structuhd_1_1system__error" ],
      [ "task", "classuhd_1_1task.html", "classuhd_1_1task" ],
      [ "time_spec_t", "classuhd_1_1time__spec__t.html", "classuhd_1_1time__spec__t" ],
      [ "timed_wb_iface", "classuhd_1_1timed__wb__iface.html", "classuhd_1_1timed__wb__iface" ],
      [ "tune_request_t", "structuhd_1_1tune__request__t.html", "structuhd_1_1tune__request__t" ],
      [ "tune_result_t", "structuhd_1_1tune__result__t.html", "structuhd_1_1tune__result__t" ],
      [ "tx_metadata_t", "structuhd_1_1tx__metadata__t.html", "structuhd_1_1tx__metadata__t" ],
      [ "tx_streamer", "classuhd_1_1tx__streamer.html", "classuhd_1_1tx__streamer" ],
      [ "type_error", "structuhd_1_1type__error.html", "structuhd_1_1type__error" ],
      [ "uart_iface", "classuhd_1_1uart__iface.html", "classuhd_1_1uart__iface" ],
      [ "usb_error", "structuhd_1_1usb__error.html", "structuhd_1_1usb__error" ],
      [ "value_error", "structuhd_1_1value__error.html", "structuhd_1_1value__error" ],
      [ "wb_iface", "classuhd_1_1wb__iface.html", "classuhd_1_1wb__iface" ]
    ] ],
    [ "_uhd_static_fixture", "struct__uhd__static__fixture.html", "struct__uhd__static__fixture" ],
    [ "uhd_range_t", "structuhd__range__t.html", "structuhd__range__t" ],
    [ "uhd_stream_args_t", "structuhd__stream__args__t.html", "structuhd__stream__args__t" ],
    [ "uhd_stream_cmd_t", "structuhd__stream__cmd__t.html", "structuhd__stream__cmd__t" ],
    [ "uhd_subdev_spec_pair_t", "structuhd__subdev__spec__pair__t.html", "structuhd__subdev__spec__pair__t" ],
    [ "uhd_tune_request_t", "structuhd__tune__request__t.html", "structuhd__tune__request__t" ],
    [ "uhd_tune_result_t", "structuhd__tune__result__t.html", "structuhd__tune__result__t" ],
    [ "uhd_usrp_register_info_t", "structuhd__usrp__register__info__t.html", "structuhd__usrp__register__info__t" ],
    [ "uhd_usrp_rx_info_t", "structuhd__usrp__rx__info__t.html", "structuhd__usrp__rx__info__t" ],
    [ "uhd_usrp_tx_info_t", "structuhd__usrp__tx__info__t.html", "structuhd__usrp__tx__info__t" ]
];